locations/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
]

talent_bridged/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.views.generic import RedirectView
from django.conf.urls.static import static
from django.conf import settings
import time
import sys
from django.urls import re_path
from account.views import (
    CustomPasswordResetView,
    LogoutView,
    LoginView,
    AccountView,
#     AccountUpdateView,
    RegistrationView,
    activate,
    ResendActivationEmailView
)

from .views import (
     home_view,
     terms_and_condition_view,
     privacy_policy_view,
     data_protection_policy_view,
     data_processing_agreement_view,
     affiliate_program_view,
     proxy_aggregator_view
)

from emails_manager.views import (
     contact_view,
     get_otp_view,
)



def trigger_error(request):
    division_by_zero = 1 / 0

def large_resource(request):
   time.sleep(4)
   return HttpResponse("Done!")

urlpatterns = [
    # Admin URL
    path('django-admin/', admin.site.urls, name='admin'),

    # Dashboard Views
    path('', home_view, name='home'),

    path('home/', include('admin_panel.urls')),


    path('contact/', contact_view, name='contact'),
    path('get-otp', get_otp_view, name='get-otp'),

    # Extra Information View
    path('terms-and-conditions/', terms_and_condition_view, name='terms_and_conditions'),
    path('privacy-policy/', privacy_policy_view, name='privacy_policy'),
    path('data-protection-policy/', data_protection_policy_view, name='data_protection_policy'),
    path('data-protection-policy/', data_processing_agreement_view, name='data_processing_agreement'),
    path('affiliate-program/', affiliate_program_view, name='affiliate_program'),
    path('proxy-aggregator-view/', proxy_aggregator_view, name='proxy_aggregator_view'),

    path('support/',contact_view  , name='support'),

    #Auth Views
    path('register/', RegistrationView.as_view(), name='register'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('login/', LoginView.as_view(), name='login'),
    path('account/', AccountView.as_view(), name='account'),
    
#     path('account/<pk>/update', AccountUpdateView.as_view(), name='account_update'),
    re_path(r'activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,40})/', 
            activate, name='account_activate'),
    path('password_change/done/',
         auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'),
         name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'),
         name='password_change'),

    path('password_reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
         name='password_reset_done'),

    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_change.html'),
         name='password_reset_confirm'),

    path('password_reset/', CustomPasswordResetView.as_view(), name='password_reset'),

    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
         name='password_reset_complete'),
         
    path("resend-activation-email/", ResendActivationEmailView.as_view(), name="resend_activation_email"),


    #sentry test view 
    path('sentry-debug/', trigger_error),
    path('large_resource/', large_resource)
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'account.views.error_404'
handler500 = 'account.views.error_500'
handler403 = 'account.views.error_403'
handler400 = 'account.views.error_400'

# Check if the current command is not related to migrations
# if 'migrate' not in sys.argv and 'makemigrations' not in sys.argv:
#     # Only call this function if it's not during migrations
#     start_initial_proxies()

account/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, _unicode_ci_compare, UserChangeForm
from django.contrib.auth.tokens import default_token_generator
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import EmailMultiAlternatives
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode

from account.models import Account
from django.contrib.auth import authenticate, get_user_model, password_validation
from django.utils.translation import gettext_lazy as _
from django.template import loader
from django.core.validators import EmailValidator

UserModel = get_user_model()

from django.conf import settings
from mailjet_rest import Client

# Django Admin forms

class CustomAccountCreationForm(UserCreationForm):
    class Meta:
        model = Account
        fields = ('email', 'username', 'name', 'password1', 'password2', 'profile_photo')
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Example: Add custom CSS classes to fields
        self.fields['email'].widget.attrs.update({'class': 'form-control'})
        self.fields['username'].widget.attrs.update({'class': 'form-control'})
        self.fields['password1'].widget.attrs.update({'class': 'form-control'})
        self.fields['password2'].widget.attrs.update({'class': 'form-control'})

    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = self.cleaned_data['email']
        user.username = self.cleaned_data['username']
        if commit:
            user.save()
        return user

class CustomAccountUpdateForm(UserChangeForm):
    class Meta:
        model = Account
        fields = ('email', 'username', 'is_active', 'is_staff', 'is_admin', 'profile_photo', 'name')

    # Override the __init__ method to customize the form if needed
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Example: Add custom CSS classes to fields
        self.fields['email'].widget.attrs.update({'class': 'form-control'})
        self.fields['username'].widget.attrs.update({'class': 'form-control'})
        # Add additional customizations here

class LoginForm(forms.Form):
    username = forms.EmailField(
        error_messages={
            'required': "Please Enter your Email",
            'invalid': "Enter a valid email address"
        },
        widget=forms.EmailInput(
            attrs={
                "placeholder": "Email",
                "class": "form-control"
            }
        ),
        validators=[EmailValidator()]
    )
    password = forms.CharField(
        error_messages={
            'required': "Please Enter your Password"
        },
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Password",
                "class": "form-control"
            }
        )
    )


class RegistrationForm(UserCreationForm):
    username = forms.CharField(
        error_messages={
            'required': "Please Enter your Username"
        },
        widget=forms.TextInput(
            attrs={
                "placeholder": "Username",
                "class": "form-control"

            }
        ))

    password1 = forms.CharField(
        error_messages={
            'required': "Please Enter your Password"
        },
        label=_("Password"),
        help_text=password_validation.password_validators_help_text_html(),
        strip=False,
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Password1",
                "class": "form-control",
                "autocomplete": "new-password"
            }
        ))

    password2 = forms.CharField(
        error_messages={
            'required': "Please Enter your Password Again"
        },
        label=_("Password confirmation"),
        help_text=_("Enter the same password as before, for verification."),
        strip=False,
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Password2",
                "class": "form-control",
                "autocomplete": "new-password"
            }
        ))

    email = forms.EmailField(
        max_length=60,
        help_text='Required. Add a valid email',
        widget=forms.EmailInput(
            attrs={
                "placeholder": "Email",
                "class": "form-control"
            }
        )
    )

    class Meta:
        model = Account
        fields = ("email", "username", "password1", "password2")


class AccountAuthenticationForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)

    class Meta:
        model = Account
        fields = ("email", "password")

    def clean(self):
        if self.is_valid():
            email = self.cleaned_data['email']
            password = self.cleaned_data['password']

            if not authenticate(email=email, password=password):
                raise forms.ValidationError("Invalid Credentials")


class AccountUpdateForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = ('email', 'username', 'profile_photo', 'name')
        widgets = {
            'email': forms.TextInput(attrs={'class': 'form-control'}),
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'profile_photo': forms.FileInput(attrs={'class': 'form-control'})
        }

    def clean_email(self):
        if self.is_valid():
            email = self.cleaned_data['email']
            try:
                account = Account.objects.exclude(pk=self.instance.pk).get(email=email)
            except Account.DoesNotExist:
                return email
            raise forms.ValidationError('Email "%s" is already in use.' % email)

    def clean_username(self):
        if self.is_valid():
            username = self.cleaned_data['username']
            try:
                account = Account.objects.exclude(pk=self.instance.pk).get(username=username)
            except Account.DoesNotExist:
                return username


class PasswordResetForm(forms.Form):
    email = forms.EmailField(
        label=_("Email"),
        max_length=254,
        widget=forms.EmailInput(attrs={"autocomplete": "email"}),
    )

    def send_mail(
            self,
            subject_template_name,
            email_template_name,
            context,
            from_email,
            to_email,
            html_email_template_name=None,
            user=None
    ):
        """
        Send a django.core.mail.EmailMultiAlternatives to `to_email`.
        """
        subject = loader.render_to_string(subject_template_name, context)
        # Email subject *must not* contain newlines
        subject = "".join(subject.splitlines())
        body = loader.render_to_string(email_template_name, context)

        if html_email_template_name is not None:
            html_email = loader.render_to_string(html_email_template_name, context)

        mailjet = Client(auth=(settings.MAIL_JET_API_KEY, settings.MAIL_JET_API_SECRET), version='v3.1')
        data = {
            'Messages': [
                {
                    "From": {
                        "Email": settings.MAIL_JET_VERIFICATION_EMAIL,
                        "Name": "Talent Bridged"
                    },
                    "To": [
                        {
                            "Email": to_email,
                            "Name": user.username
                        }
                    ],
                    "Subject": subject,
                    "TextPart": body,
                    "HTMLPart": body,
                    "CustomID": f"{user.email}"
                }
            ]
        }
        result = mailjet.send.create(data=data)
        if result:
            print(f"Mail Send Successfully {result}")
        else:
            print(f"Mail Send Failed {result}")

    def get_users(self, email):
        """Given an email, return matching user(s) who should receive a reset.

        This allows subclasses to more easily customize the default policies
        that prevent inactive users and users with unusable passwords from
        resetting their password.
        """
        email_field_name = UserModel.get_email_field_name()
        active_users = UserModel._default_manager.filter(
            **{
                "%s__iexact" % email_field_name: email,
                "is_active": True,
            }
        )
        return (
            u
            for u in active_users
            if u.has_usable_password()
               and _unicode_ci_compare(email, getattr(u, email_field_name))
        )

    def save(
            self,
            domain_override=None,
            subject_template_name="registration/password_reset_subject.txt",
            email_template_name="registration/password_reset_email.html",
            use_https=False,
            token_generator=default_token_generator,
            from_email=None,
            request=None,
            html_email_template_name=None,
            extra_email_context=None,
    ):
        """
        Generate a one-use only link for resetting password and send it to the
        user.
        """
        email = self.cleaned_data["email"]
        if not domain_override:
            current_site = get_current_site(request)
            site_name = current_site.name
            domain = current_site.domain
        else:
            site_name = domain = domain_override
        email_field_name = UserModel.get_email_field_name()
        for user in self.get_users(email):
            user_email = getattr(user, email_field_name)
            context = {
                "email": user_email,
                "domain": domain,
                "site_name": site_name,
                "uid": urlsafe_base64_encode(force_bytes(user.pk)),

templates/extras/coming_soon.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Affiliate Program | Talent Bridged{% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}
<style>
    .coming-soon-container {
        text-align: center;
        margin-top: 100px;
    }

    h1 {
        font-size: 72px;
        font-weight: bold;
        background: linear-gradient(45deg, #ff6b6b, #5f27cd);
        -webkit-background-clip: text;
        color: transparent;
        animation: glow 1.5s ease-in-out infinite alternate;
    }

    @keyframes glow {
        from {  
            text-shadow: 0 0 10px #5f27cd, 0 0 20px #ff6b6b, 0 0 30px #ff6b6b;
        }
        to {
            text-shadow: 0 0 20px #5f27cd, 0 0 30px #ff6b6b, 0 0 40px #ff6b6b;
        }
    }

    .message {
        margin-top: 20px;
        font-size: 20px;
        color: #333;
        max-width: 600px;
        margin-left: auto;
        margin-right: auto;
    }

    .message p {
        margin: 20px 0;
    }

    .social-links {
        margin-top: 20px;
    }

    .social-links a {
        margin: 0 15px;
        color: #333;
        font-size: 24px;
        text-decoration: none;
    }

    .social-links a:hover {
        color: #5f27cd;
    }

    .footer {
        text-align: center;
        margin-top: 40px;
        color: #888;
    }

    @media (max-width: 768px) {
        h1 {
            font-size: 48px;
        }

        .message {
            font-size: 18px;
        }

        .social-links a {
            font-size: 20px;
        }
    }
</style>
{% endblock stylesheets %}

{% block content %}
<div class="coming-soon-container">
    <h1>COMING SOON</h1>
    <div class="message">
        <p>Our Affiliate Program will be launching soon. Make sure to subscribe to our newsletter and follow us on social media for the latest updates and an official announcement of our launch.</p>
        <p>We can't wait to partner with you in this exciting new journey!</p>
    </div>
    
    <div class="social-links">
        <a href="https://www.instagram.com/scrapeoptimus/"><i class="fab fa-instagram"></i></a>
        <a href="https://www.facebook.com/profile.php?id=61566415477872"><i class="fab fa-facebook-f"></i></a>
        <a href="https://x.com/scrapeoptimus"><i class="fab fa-twitter"></i></a>
        <a href="mailto:support@scrapeoptimus.com"><i class="fas fa-envelope"></i></a>
    </div>
</div>
{% endblock content %}

<!-- Specific JS goes HERE -->
{% block javascripts %}
<!-- Font Awesome for Social Icons -->
<script src="https://kit.fontawesome.com/a076d05399.js"></script>
{% endblock javascripts %}

templates/extras/contact.html
{% extends 'base.html' %}
{% load static %}

{% block stylesheets %}
{% endblock stylesheets %}
{% block content %}

<!-- start contact us -->
<section class="section bg-light" id="contact" style="padding: 20px 0;">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="card bg-white">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-8">
                                <h2 class="fs-2 fw-normal lh-1 text-dark mb-3">Get in touch!</h2>
                                <p class="text-gray-700 fs-18 fs-lg mb-4 mb-md-5 ">
                                Whether you have a question or just want to know anything, We’ll try my best to get back to you as soon as possible!</p>
                                <form method="post" name="myForm" onsubmit="return validateForm()">
                                    {% csrf_token %}
                                    <span id="error-msg"></span>
                                    <div class="row">
                                        <div class="col-md-6 mb-3">
                                            <label class="fw-medium form-label fs-16" for="name">Name</label>
                                            {{ form.name }}
                                        </div>
                                        <!-- end col -->
                                        <div class="col-md-6 mb-3" id="email-div">
                                            <label class="fw-medium form-label  fs-16" for="email">Email</label>
                                            {{ form.email }}
                                        </div>
                                        <!-- end col -->
                                        <div class="col-md-6 mb-3">
                                            <label class="fw-medium form-label fs-16" for="otp">One Time Password</label>
                                            <input type="text" class="form-control" placeholder="One Time Password" id="otp" name="otp"/>
                                            {{ form.otp }}
                                        </div>
                                        <div class="col-md-6 mb-6" style="margin-top: 30px" >
                                            <button type="button" class="btn btn-secondary btn-lg" style="background-color: #4f66ff;" id="get_otp">Get One Time Password</button>
                                        </div>
                                        <!-- end col -->
                                        <div class="col-md-6 mb-3" >
                                            <label class="fw-medium form-label  fs-16" for="subject">Subject</label>
                                            {{ form.subject }}
                                        </div>
                                        <!-- end col -->
                                        <div class="col-md-6 mb-3">
                                            <label class="fw-medium form-label  fs-16" for="number">Contact</label>
                                            {{ form.contact }}
                                        </div>
                                        <!-- end col -->
                                        <div class="col-12 mb-3">
                                            <label class="fw-medium form-label  fs-16" for="comments">Message</label>
                                            {{ form.message }}
                                        </div>
                                        <!-- end col -->
                                        <div class="col-12">
                                            <input type="submit" id="submit" name="send" class="btn btn-primary mt-2" value="Send message" style="background-color: #8c52ff; border-color: #8c52ff;"/>
                                        </div>
                                        

                                        <!-- end col -->
                                    </div><!--end row-->
                                </form><!-- end form -->
                            </div><!-- end col -->
                            <div class="col-md-4">
                                <img src="{% static 'images/personal/contact.svg' %}" alt="" height="200" class=" mx-auto d-block mb-5">
                                <div class="d-flex">
                                    <div class="bg-light d-flex justify-content-center align-items-center thumb-lg  rounded">
                                        <i class="ti ti-phone fs-22"></i>
                                    </div>
                                    <div class="align-self-center ms-3">
                                        <span class="d-block lh-1">+91 7470706663</span>
                                        <span class="text-muted fs-14 mt-n2">9:00am to 7:00pm</span>
                                    </div>
                                </div>
                                <hr class="hr-dashed my-3">
                                <div class="d-flex">
                                    <div class="bg-light d-flex justify-content-center align-items-center thumb-lg  rounded">
                                        <i class="ti ti-mail fs-22"></i>
                                    </div>
                                    <div class="align-self-center ms-3">
                                        <span class="d-block lh-1">support@scrapeoptimus.com</span>
                                        <span class="text-muted fs-14 mt-n2">Monday to Sunday</span>
                                    </div>
                                </div>
                            </div><!--end col-->
                        </div><!-- end row -->
                    </div><!--end card-body-->
                </div><!--end card-->
            </div><!-- end col -->
        </div><!-- end row -->
    </div><!-- end container -->
</section>

{% endblock content %}

{% block javascripts %}
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script>
    $(document).ready(function() {
        function getCookie(name) {
            let cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                const cookies = document.cookie.split(';');
                for (let i = 0; i < cookies.length; i++) {
                    const cookie = cookies[i].trim();
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }

        const csrftoken = getCookie('csrftoken');

        $('#get_otp').on('click', function(e) {
            e.preventDefault();
            let email = $('#id_email').val();

            $.ajax({
                type: 'POST',
                url: "{% url 'get-otp' %}",
                data: {
                    email: email,
                    csrfmiddlewaretoken: csrftoken
                },
                dataType: 'json',
                success: function(data) {
                    Swal.fire({
                        icon: 'success',
                        title: 'Success',
                        text: data.message,
                    }).then(() => {
                        $('#get_otp').css('background-color', 'green');
                        $('#get_otp').text('One Time Password Sent | Resend');
                    });
                },
                error: function(data) {
                    Swal.fire({
                        icon: 'error',
                        title: 'Oops...',
                        text: data.responseJSON.message,
                    });
                }
            });
        });

        $('form[name="myForm"]').on('submit', function(e) {
            e.preventDefault(); // Prevent form submission
            const formData = $(this).serialize(); // Serialize form data

            $.ajax({
                type: 'POST',
                url: "{% url 'contact' %}",
                data: formData,
                dataType: 'json',
                success: function(data) {
                    Swal.fire({
                        icon: 'success',
                        title: 'Thank you!',
                        text: data.message,
                    }).then(() => {
                        // Clear the form fields
                        $('form[name="myForm"]')[0].reset();
                        $('#get_otp').css('background-color', '#8392AB');
                        $('#get_otp').text('One Time Password');
                    });
                },
                error: function(data) {
                    Swal.fire({
                        icon: 'error',
                        title: 'Oops...',
                        text: data.responseJSON.message,
                    });
                    $('form[name="myForm"]')[0].reset();
                    $('#get_otp').css('background-color', '#8392AB');
                    $('#get_otp').text('One Time Password');
                }
            });
        });
    });
</script>
{% endblock javascripts %}

templates/extras/data_protection_policy.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Data Protection Policy | Talent Bridged{% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}
<style>
    .data-protection-header {
        text-align: center;
        margin-bottom: 40px;
    }

    .data-protection-header h1 {
        font-size: 36px;
        color: #333;
    }

    .data-protection-header p {
        font-size: 18px;
        color: #888;
    }

    .data-protection-body {
        display: flex;
        justify-content: space-between;
    }

    .data-protection-content {
        width: 85%; /* Main content section takes up 85% of the width */
    }

    .data-protection-sidebar {
        width: 15%; /* Sidebar takes up 15% of the width */
        padding-left: 20px;
    }

    .data-protection-sidebar ul {
        list-style-type: none;
        padding: 0;
    }

    .data-protection-sidebar li {
        margin-bottom: 10px;
    }

    .data-protection-sidebar li a {
        text-decoration: none;
        color: #007bff;
        font-weight: bold;
    }

    h2 {
        margin-top: 30px;
        font-size: 24px;
        color: #333;
    }

    h3 {
        margin-top: 20px;
        font-size: 20px;
        color: #555;
    }

    p {
        margin: 20px 0;
        line-height: 1.6;
    }
</style>
{% endblock stylesheets %}

{% block content %}
<div class="container">
    <div class="data-protection-header">
        <h1>Data Protection Policy</h1>
        <p>General Data Protection Regulation</p>
    </div>

    <div class="data-protection-body">
        <!-- Main Content Section -->
        <div class="data-protection-content">
            <h2 id="gdpr">General Data Protection Regulation</h2>
            <p>The General Data Protection Regulation (GDPR) is European Union legislation to strengthen and unify data protection laws for all individuals within the European Union. The regulation came into effect on May 25th, 2018.</p>

            <p>As an Irish business, founded and run by Irish citizens, but also as people who value privacy, we are fully committed to being compliant with GDPR and all data protection best practices.</p>

            <p>This page lays out our commitment to data protection and makes transparent what data we store about our users.</p>

            <h2 id="who-we-are">Who We Are</h2>
            <p>Our company, TalentBridged Ltd, is a limited company by shares in Ireland.</p>

            <h2 id="questions">Questions?</h2>
            <p>If you have any questions regarding this topic, feel free to send us an email at <strong>support@scrapeoptimus.com</strong>.</p>

            <h2 id="data-collect">What Data Do We Collect?</h2>

            <h3 id="on-website">On Our Website</h3>
            <p>Our website is hosted by Digital Ocean in London. On our website, we use Google Analytics to help us understand, in anonymized form, how the site is being used.</p>

            <p>When registering for our free trial, you need to provide us with a valid email address. We confirm that the address works by emailing you a confirmation link. We use SendGrid, operated by Twilio Inc, for email delivery. Twilio privacy policy is available <a href="https://www.twilio.com/legal/privacy" target="_blank">here</a>.</p>

            <h3 id="on-api">On Our API</h3>
            <p>Our API servers are hosted with Digital Ocean. When our SDK is installed and active, data based on the ongoing scraping activity is sent to us. We send you a response and log the details. We use Datadog for log management, and logs are deleted after 14 days.</p>

            <h3 id="customer-financial">Customer/Financial Transaction Information</h3>
            <p>If you become a paying customer, we collect valid billing information, including name, billing address, email, and VAT number. Payment processing is handled by Stripe, and invoicing is managed by Chargebee.</p>

            <h2 id="data-processing-agreement">Data Processing Agreement</h2>
            <p>Becoming a customer of our service implies acceptance of our <a href="#">Data Processing Agreement</a>, unless otherwise explicitly agreed with us in writing.</p>

            <h2 id="data-deletion">Data Deletion</h2>
            <p>Any user (paid or free-trial) can request to have their account deleted at any time by contacting us at <strong>support@scrapeoptimus.com</strong>. For paying customers, we must retain records of completed transactions for tax purposes.</p>
        </div>

        <!-- Sidebar with links -->
        <div class="data-protection-sidebar">
            <ul>
                <li><a href="#gdpr">General Data Protection Regulation</a></li>
                <li><a href="#who-we-are">Who We Are</a></li>
                <li><a href="#questions">Questions?</a></li>
                <li><a href="#data-collect">What Data Do We Collect?</a></li>
                <li><a href="#on-website">On Our Website</a></li>
                <li><a href="#on-api">On Our API</a></li>
                <li><a href="#customer-financial">Customer/Financial Transaction Information</a></li>
                <li><a href="#data-processing-agreement">Data Processing Agreement</a></li>
                <li><a href="#data-deletion">Data Deletion</a></li>
            </ul>
        </div>
    </div>
</div>
{% endblock content %}

<!-- Specific JS goes HERE -->
{% block javascripts %}
<!-- Any specific JavaScript for this page -->
{% endblock javascripts %}